[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Videos"
  url = "post/rich-content/"
  weight = -105
[[main]]
  name = "What is LEAP?"
  url = "post/starting-a-project/"
  weight = -107

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "Paludarium Dashboard (Not currently Public)"
  url = ""
[[main]]
  parent = "Links"
  name = "Paludarium Livestream (W.I.P)"
  url = ""
[[main]]
  parent = "Links"
  name = "Fight Hunger!"
  url = "https://hungerfreecolorado.org/"

[[main]]
  name = "About Me"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/CyrusDS"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/CyrusDS"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/cyrus-sowdaey-963271166/"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"